In [1]:
import numpy as np
import pandas as pd

In [80]:
df = pd.read_csv('data.txt')

In [27]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [10]:
df.MSRP[
    df['Make'] == 'BMW'
].mean()

61546.76347305389

In [15]:
df['Engine HP'][
    df['Year'] >= 2015
].isnull().sum()

51

In [32]:
mean_hp_before = df['Engine HP'].mean()
print(round(mean_hp_before))

249


In [29]:
df['Engine HP'].fillna(value=mean_hp_before)

0        335.0
1        300.0
2        300.0
3        230.0
4        230.0
         ...  
11909    300.0
11910    300.0
11911    300.0
11912    300.0
11913    221.0
Name: Engine HP, Length: 11914, dtype: float64

In [33]:
mean_hp_after = df['Engine HP'].mean()
print(round(mean_hp_after))

249


In [81]:
df1 = df[
    df.Make == 'Rolls-Royce'
]

In [82]:
df6 = df1[['Engine HP', 'Engine Cylinders', 'highway MPG']]

In [85]:
df6 =df6.drop_duplicates()

In [86]:
X= df6.values
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [87]:
X.T

array([[325., 563., 563., 563., 322., 453., 624.],
       [  8.,  12.,  12.,  12.,  12.,  12.,  12.],
       [ 15.,  19.,  21.,  20.,  15.,  19.,  21.]])

In [88]:
XTX = (X.T).dot(X)
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [89]:
inv = np.linalg.inv(XTX)
inv

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [90]:
np.sum(inv)

0.03221232067748617

In [93]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])

In [96]:
w= (inv.dot(X.T)).dot(y)
w

array([ 0.19989598, 31.02612262, 31.65378877])